%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-easynav
Version:        0.1.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS easynav package

License:        GPL-3.0-only
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-easynav-common
Requires:       ros-jazzy-easynav-controller
Requires:       ros-jazzy-easynav-core
Requires:       ros-jazzy-easynav-interfaces
Requires:       ros-jazzy-easynav-localizer
Requires:       ros-jazzy-easynav-maps-manager
Requires:       ros-jazzy-easynav-planner
Requires:       ros-jazzy-easynav-sensors
Requires:       ros-jazzy-easynav-support-py
Requires:       ros-jazzy-easynav-system
Requires:       ros-jazzy-easynav-tools
Requires:       ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-easynav-common
BuildRequires:  ros-jazzy-easynav-controller
BuildRequires:  ros-jazzy-easynav-core
BuildRequires:  ros-jazzy-easynav-interfaces
BuildRequires:  ros-jazzy-easynav-localizer
BuildRequires:  ros-jazzy-easynav-maps-manager
BuildRequires:  ros-jazzy-easynav-planner
BuildRequires:  ros-jazzy-easynav-sensors
BuildRequires:  ros-jazzy-easynav-support-py
BuildRequires:  ros-jazzy-easynav-system
BuildRequires:  ros-jazzy-easynav-tools
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Easy Navigation:Mata package for installing all EasyNav.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Thu Oct 16 2025 Francisco Martín Rico <fmrico@gmail.com> - 0.1.4-1
- Autogenerated by Bloom

