name: humble

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: humble
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: easynav_common easynav_controller easynav_core easynav_interfaces easynav_localizer easynav_maps_manager easynav_planner easynav_sensors easynav_system easynav_support_py easynav_tools
          target-ros2-distro: humble
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/.github/thirdparty.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"],
                "parallel-workers": 1
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/b8436aa16c0bdbc01081b12caa253cbf16e0fb82/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
